defaults: &defaults
  endpoints:
    rsapi_batch_user_get: /service_api/users
    rsapi_batch_delete: /service_api/users/batch_gdpr
    rsapi_user_get: /service_api/data/user
    entity_service_batch_delete: /v1/users/batch
    dsapi_batch_delete_user_ids: /api/users/gdpr_user_ids_batch
    dsapi_batch_delete_user_record_ids: /api/users/gdpr_user_record_ids_batch
    dsapi_batch_delete_user_emails: /api/users/gdpr_emails_batch
    predictinator_batch_delete: /v2/users
    subscription_lambda_batch_delete_user_ids: /v1/users

production:
  env: prd
  environment: production
  <<: *defaults

staging:
  env: stg
  environment: staging
  <<: *defaults